import FourColorTheorem.FourColor.Reducibility.KernelCertificate.IndexedReplay

namespace Schematic.Math.GraphTheory.FourColor.KernelCertificate

set_option maxRecDepth 100000 in
def config164Stage011Refs331 : RefTrie :=
  RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 39) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 40) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 41) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node (some 42) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty) (RefTrie.empty)) (RefTrie.empty))) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 43) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 44) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 45) RefTrie.empty RefTrie.empty RefTrie.empty))) (RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)

set_option maxRecDepth 100000 in
def config164Stage011Refs332 : RefTrie :=
  RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 46) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 47) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 48) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node (some 49) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty) (RefTrie.empty)) (RefTrie.empty))) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 50) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 51) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 52) RefTrie.empty RefTrie.empty RefTrie.empty))) (RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)

set_option maxRecDepth 100000 in
def config164Stage011Refs333 : RefTrie :=
  RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 53) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 54) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 55) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node (some 56) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty) (RefTrie.empty)) (RefTrie.empty))) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 57) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 58) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 59) RefTrie.empty RefTrie.empty RefTrie.empty))) (RefTrie.empty))) (RefTrie.empty) (RefTrie.empty))

end Schematic.Math.GraphTheory.FourColor.KernelCertificate
