import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164Segments.Common
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerData.Table
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerEntryData.Segment217

namespace Schematic.Math.GraphTheory.FourColor.KernelCertificate

config164_owner_segment_certificate config164_segment217_verified and
  config164_segment217_sound using config164OwnerEntries217
  from 52091 to 52219

end Schematic.Math.GraphTheory.FourColor.KernelCertificate
