import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164Segments.Common
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerData.Table
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerEntryData.Segment268

namespace Schematic.Math.GraphTheory.FourColor.KernelCertificate

config164_owner_segment_certificate config164_segment268_verified and
  config164_segment268_sound using config164OwnerEntries268
  from 58619 to 58747

end Schematic.Math.GraphTheory.FourColor.KernelCertificate
