import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164Segments.Common
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerData.Table
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerEntryData.Segment099

namespace Schematic.Math.GraphTheory.FourColor.KernelCertificate

config164_owner_segment_certificate config164_segment099_verified and
  config164_segment099_sound using config164OwnerEntries099
  from 36987 to 37115

end Schematic.Math.GraphTheory.FourColor.KernelCertificate
