import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164Segments.Common
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerData.Table
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerEntryData.Segment258

namespace Schematic.Math.GraphTheory.FourColor.KernelCertificate

config164_owner_segment_certificate config164_segment258_verified and
  config164_segment258_sound using config164OwnerEntries258
  from 57339 to 57467

end Schematic.Math.GraphTheory.FourColor.KernelCertificate
