import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164Segments.Common
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerData.Table
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164OwnerEntryData.Segment283

namespace Schematic.Math.GraphTheory.FourColor.KernelCertificate

config164_owner_segment_certificate config164_segment283_verified and
  config164_segment283_sound using config164OwnerEntries283
  from 60539 to 60667

end Schematic.Math.GraphTheory.FourColor.KernelCertificate
