import FourColorTheorem.FourColor.Reducibility.KernelCertificate.IndexedReplay

namespace Schematic.Math.GraphTheory.FourColor.KernelCertificate

set_option maxRecDepth 100000 in
def config164Stage014Refs311 : RefTrie :=
  RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 78) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 79) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 80) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty))) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 81) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 82) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 83) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 84) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)))) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 85) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 86) RefTrie.empty RefTrie.empty RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 87) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 88) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)))) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 89) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 90) RefTrie.empty RefTrie.empty RefTrie.empty)))))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)

set_option maxRecDepth 100000 in
def config164Stage014Refs312 : RefTrie :=
  RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 91) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 92) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 93) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty))) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 94) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 95) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 96) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 97) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)))) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 98) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 99) RefTrie.empty RefTrie.empty RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 100) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 101) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)))) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 102) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 103) RefTrie.empty RefTrie.empty RefTrie.empty)))))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)

set_option maxRecDepth 100000 in
def config164Stage014Refs313 : RefTrie :=
  RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 104) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 105) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 106) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty))) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 107) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 108) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 109) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 110) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty) (RefTrie.empty)))) (RefTrie.empty) (RefTrie.node none (RefTrie.node none (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 111) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 112) RefTrie.empty RefTrie.empty RefTrie.empty))) (RefTrie.empty) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 113) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node (some 114) RefTrie.empty RefTrie.empty RefTrie.empty) (RefTrie.empty)))) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 115) RefTrie.empty RefTrie.empty RefTrie.empty)) (RefTrie.empty)) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node none (RefTrie.empty) (RefTrie.empty) (RefTrie.node (some 116) RefTrie.empty RefTrie.empty RefTrie.empty)))))) (RefTrie.empty) (RefTrie.empty))

end Schematic.Math.GraphTheory.FourColor.KernelCertificate
