import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage026.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage026.Refs
