import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage031.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage031.Refs
