import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage003.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage003.Refs
