import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage015.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage015.Refs
