import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage018.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage018.Refs
