import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage033.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage033.Refs
