import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage020.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage020.Refs
