import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage010.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage010.Refs
