import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage017.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage017.Refs
