import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage006.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage006.Refs
