import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage008.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage008.Refs
