import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage013.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage013.Refs
