import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage002.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage002.Refs
