import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage012.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage012.Refs
