import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage009.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage009.Refs
