import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage001.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage001.Refs
