import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage024.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage024.Refs
