import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage007.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage007.Refs
