import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage029.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage029.Refs
