import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage011.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage011.Refs
