import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage034.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage034.Refs
