import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage005.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage005.Refs
