import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage004.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage004.Refs
