import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage022.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage022.Refs
