import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage028.Source
import FourColorTheorem.FourColor.Reducibility.KernelCertificate.Config164ProgramData.Stage028.Refs
