import FourColorTheorem.FourColor.Reducibility.CFContract.Complete

/-!
Semantic bridge from kernel certificates to configuration reducibility.

The certificate proves that every trace in the contracted colouring tree is
in the Kempe co-closure generated by the configuration's ordinary colouring
tree.  `Config.contractTree_complete` supplies the map-theoretic contract
semantics, and the final rotation argument is the same one used by the
standard executable checker.
-/

namespace Schematic.Math.GraphTheory

namespace FourColor

namespace KernelCertificate

/-- Declarative configuration colourings seed the required rotated-boundary
Kempe co-closure. -/
theorem configColorSpec_coclosure
    {cf : Config} (hcfg : CProg.config cf.program = true)
    {et : ColSeq} (hspec : CProg.cpColorSpec cf.program et) :
    Chromogram.KempeCoclosure
      (fun cet => cf.map.map.RingTrace
        (CProg.rotateLeft 1 cf.ringDarts) cet)
      (ColSeq.ctrace et) := by
  apply Chromogram.KempeCoclosure.of_mem
  have htrace := PointedHypermap.cpColorSpec_ringTrace_of_config hcfg hspec
  have hrot := Config.ringTrace_rotateLeft_boundary htrace 1
  simpa [CProg.rotateLeft_one_cons, ColSeq.ctrace] using hrot

/-- Ordinary configuration traces seed the required rotated-boundary Kempe
co-closure. -/
theorem configColorTree_coclosure
    {cf : Config} (hcfg : CProg.config cf.program = true) :
    ∀ xs : ColSeq, CTree.mem (CProg.cpColorFast cf.program) xs = true →
      Chromogram.KempeCoclosure
        (fun cet => cf.map.map.RingTrace
          (CProg.rotateLeft 1 cf.ringDarts) cet)
        (ColSeq.ctrace xs) := by
  intro xs hmem
  have hmem' : CTree.mem (CProg.cpColor cf.program) xs = true := by
    simpa [CProg.cpColorFast_spec] using hmem
  rcases (PointedHypermap.ctree_mem_cpColor_iff_of_config hcfg xs).1
      hmem' with ⟨_heven, htrace⟩
  apply Chromogram.KempeCoclosure.of_mem
  have hrot := Config.ringTrace_rotateLeft_boundary htrace 1
  simpa [CProg.rotateLeft_one_cons, ColSeq.ctrace] using hrot

/-- Contract-tree completeness plus Kempe co-closure of every represented
trace of the forced boundary length implies semantic C-reducibility. -/
theorem cReducible_of_contractTree_coclosure_of_length
    {cf : Config} {target : CTree}
    (hcontract : cf.contractTree = some target)
    (htarget : ∀ xs : ColSeq, CTree.mem target xs = true →
      xs.length = CProg.ringSize cf.program - 1 →
      Chromogram.KempeCoclosure
        (fun cet => cf.map.map.RingTrace
          (CProg.rotateLeft 1 cf.ringDarts) cet)
        (ColSeq.ctrace xs)) :
    cf.map.map.CReducible cf.reducibilityRingDarts cf.contractFinset := by
  rcases Config.contractTree_complete hcontract with
    ⟨hvalid, hcompleteContract⟩
  refine ⟨hvalid, ?_⟩
  let P : ColSeq → Prop := fun cet =>
    cf.map.map.RingTrace (CProg.rotateLeft 1 cf.ringDarts) cet
  change ∀ xs : ColSeq, CTree.mem target xs = true →
    xs.length = CProg.ringSize cf.program - 1 →
      Chromogram.KempeCoclosure P (ColSeq.ctrace xs) at htarget
  intro et htrace
  have htraceRing :
      cf.map.map.ContractRingTrace cf.contractFinset cf.ringDarts et := by
    simpa using htrace
  have hetLen : et.length = CProg.ringSize cf.program := by
    simpa using Hypermap.ContractRingTrace.length
      (G := cf.map.map) htraceRing
  have hetNe : et ≠ [] := by
    apply List.ne_nil_of_length_pos
    rw [hetLen]
    exact CProg.ringSize_pos cf.program
  have hmem := hcompleteContract et htraceRing
  have hnormalizedLength :
      (ColSeq.etrace et.tail).length = CProg.ringSize cf.program - 1 := by
    rw [ColSeq.length_etrace, List.length_tail, hetLen]
  have hcocloseNormalized := htarget (ColSeq.etrace et.tail) hmem
    hnormalizedLength
  have hcocloseTail := Chromogram.KempeCoclosure.perm
    hcocloseNormalized (EdgePerm.inv (ColSeq.etracePerm et.tail))
  have hcocloseTail' :
      Chromogram.KempeCoclosure P (ColSeq.ctrace et.tail) := by
    simpa [ColSeq.etrace, ← ColSeq.perm_ctrace, ColSeq.perm_inv] using
      hcocloseTail
  have hsum : ColSeq.sum et = Color.zero :=
    Hypermap.ContractRingTrace.sum_zero (G := cf.map.map) htraceRing
  have hrot := Config.rot1_eq_ctrace_tail_of_sum_zero hetNe hsum
  have hcocloseRot :
      Chromogram.KempeCoclosure P (ColSeq.rot1 et) := by
    rwa [hrot]
  exact Config.kempeCoclosure_rot1_ringTrace_elim
    (by simpa [P] using hcocloseRot)

/-- Length-insensitive convenience form of
`cReducible_of_contractTree_coclosure_of_length`. -/
theorem cReducible_of_contractTree_coclosure
    {cf : Config} {target : CTree}
    (hcontract : cf.contractTree = some target)
    (htarget : ∀ xs : ColSeq, CTree.mem target xs = true →
      Chromogram.KempeCoclosure
        (fun cet => cf.map.map.RingTrace
          (CProg.rotateLeft 1 cf.ringDarts) cet)
        (ColSeq.ctrace xs)) :
    cf.map.map.CReducible cf.reducibilityRingDarts cf.contractFinset :=
  cReducible_of_contractTree_coclosure_of_length hcontract
    (fun xs hmem _ => htarget xs hmem)

end KernelCertificate

end FourColor

end Schematic.Math.GraphTheory
